plugins {
    id "com.android.application"
}

android {
    namespace "com.chen1.dshmobile"
    compileSdk 35

    defaultConfig {
        applicationId "com.chen1.dshmobile"
        minSdk 26
        targetSdk 35
        versionCode 5
        versionName "1.3.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "com.github.mwiede:jsch:2.28.6"
}
